# User.create!([
#   {id: 4, password: "12345678", doc_file_name: nil, doc_content_type: nil, doc_file_size: nil, doc_updated_at: nil, email: "quality@1.com", encrypted_password: "$2a$10$sdd5c9JFM8I3N/g6G.i35.GvZd1X2FfSn2.Sr5x4y7UjhBR3aNBE.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-05-28 03:29:57", last_sign_in_at: "2015-05-28 03:29:57", current_sign_in_ip: "::1", last_sign_in_ip: "::1", last_seen_at: "2015-05-28 03:30:05"},
#   {id: 6, password: "12345678", doc_file_name: nil, doc_content_type: nil, doc_file_size: nil, doc_updated_at: nil, email: "olivia@2.com", encrypted_password: "$2a$10$lRzWyghqQoKDyDPSA5mBrOx9i75llhIuQsgq9VoiNeAPJEmGJJ7ku", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-05-28 03:33:14", last_sign_in_at: "2015-05-28 03:33:14", current_sign_in_ip: "::1", last_sign_in_ip: "::1", last_seen_at: "2015-05-28 03:34:49"},
#   {id: 5, password: "12345678", doc_file_name: nil, doc_content_type: nil, doc_file_size: nil, doc_updated_at: nil, email: "quality@2.com", encrypted_password: "$2a$10$z.OvcSI9FxC1E9UFX856PuchwktcmJCvSfovEFS4M.KlnSurgYcPC", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2015-05-28 03:35:26", last_sign_in_at: "2015-05-28 03:32:24", current_sign_in_ip: "::1", last_sign_in_ip: "::1", last_seen_at: "2015-05-28 03:36:03"},
#   {id: 2, password: "12345678", doc_file_name: nil, doc_content_type: nil, doc_file_size: nil, doc_updated_at: nil, email: "mary@1.com", encrypted_password: "$2a$10$7.LeOTl9dqiPdLNAkBO8CeUX1rwireYGsOUP50fhidKYJSWE4NTsG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-05-28 03:28:40", last_sign_in_at: "2015-05-28 03:28:40", current_sign_in_ip: "::1", last_sign_in_ip: "::1", last_seen_at: "2015-05-28 03:28:48"},
#   {id: 7, password: "12345678", doc_file_name: nil, doc_content_type: nil, doc_file_size: nil, doc_updated_at: nil, email: "ken@2.com", encrypted_password: "$2a$10$YdguJZlqNxAFQJSuq3VqpumkMaa/G/AllzNsfUeBi18BJRQAbm0kG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2015-05-28 03:41:48", last_sign_in_at: "2015-05-28 03:36:45", current_sign_in_ip: "::1", last_sign_in_ip: "::1", last_seen_at: "2015-05-28 03:41:55"},
#   {id: 3, password: "12345678", doc_file_name: nil, doc_content_type: nil, doc_file_size: nil, doc_updated_at: nil, email: "bob@1.com", encrypted_password: "$2a$10$S/FwR/EzQt1fw7jrhx0F8u2qi6DSZ0pUML1wNZ5gOOAVW/vhl/lE.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-05-28 03:29:22", last_sign_in_at: "2015-05-28 03:29:22", current_sign_in_ip: "::1", last_sign_in_ip: "::1", last_seen_at: "2015-05-28 03:29:35"},
#   {id: 1, password: "12345678", doc_file_name: nil, doc_content_type: nil, doc_file_size: nil, doc_updated_at: nil, email: "owner@1.com", encrypted_password: "$2a$10$3JdJqaW5V2vFuCYiBYFNBOWe3163Df4j7eZ5/oxTVt27yuF9j8D1i", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2015-05-28 03:42:03", last_sign_in_at: "2015-05-28 03:40:56", current_sign_in_ip: "::1", last_sign_in_ip: "::1", last_seen_at: "2015-05-28 03:42:12"}
# ])
# Organisation.create!([
#   {id: 1, name: "Pharmacy", user_id: 1},
#   {id: 2, name: "Medical Advisor", user_id: 1}
# ])
# OrganisationUser.create!([
#   {id: 1, accepted: true, user_type: 2, user_id: 1, organisation_id: 1, inviter_id: 1},
#   {id: 2, accepted: true, user_type: 2, user_id: 1, organisation_id: 2, inviter_id: 1},
#   {id: 3, accepted: true, user_type: 1, user_id: 2, organisation_id: 2, inviter_id: 1},
#   {id: 4, accepted: true, user_type: 1, user_id: 3, organisation_id: 2, inviter_id: 1},
#   {id: 5, accepted: true, user_type: 0, user_id: 4, organisation_id: 2, inviter_id: 1},
#   {id: 6, accepted: true, user_type: 0, user_id: 5, organisation_id: 1, inviter_id: 1},
#   {id: 7, accepted: true, user_type: 1, user_id: 6, organisation_id: 1, inviter_id: 1},
#   {id: 8, accepted: true, user_type: 1, user_id: 7, organisation_id: 1, inviter_id: 1}
# ])
RisksImpact.create!([
  {id: 1, name: "Injury", impact: "Negligible", description: "Adverse event leading to minor injury not requiring first aid. <br /> No impaired Psychosocial functioning", value: 1},
  {id: 2, name: "Injury", impact: "Minor", description: "Minor injury or illness, first aid treatment required <br /> <3 days absence <br /> < 3 days extended hospital stay <br /> Impaired psychosocial functioning greater than 3 days less than one month", value: 2},
  {id: 3, name: "Injury", impact: "Moderate", description: "Significant injury requiring medical treatment e.g. Fracture and/or counselling. Agency reportable, e.g. HSA, Gardaí (violent and aggressive acts). >3 Days absence 3-8 Days extended hospital Stay Impaired psychosocial functioning greater than one month less than six months", value: 3},
  {id: 4, name: "Injury", impact: "Major", description: "Major injuries/long term incapacity or disability (loss of limb) requiring medical treatment and/or counselling Impaired psychosocial functioning greater than six months", value: 4},
  {id: 5, name: "Injury", impact: "Extreme", description: "Incident leading to death or major pe which impacts on large number of patients or member of the public  Permanent psychosocial  functioning incapacity.rmanent incapacity. Event", value: 5},
  {id: 6, name: "Service User Experience", impact: "Negligible", description: "Reduced quality of  service user experience related to inadequate  provision of information", value: 1},
  {id: 7, name: "Service User Experience", impact: "Minor", description: "Unsatisfactory  service user experience related to less than optimal treatment and/or inadequate information, not being to talked to & treated as an equal; or not being treated with honesty, dignity & respect - readily resolvable ", value: 2},
  {id: 8, name: "Service User Experience", impact: "Moderate", description: "Unsatisfactory service user experience related to less than optimal treatment resulting in short term effects (less than 1 week)", value: 3},
  {id: 9, name: "Service User Experience", impact: "Major", description: "Unsatisfactory service user experience related to poor treatment resulting in long term effects", value: 4},
  {id: 10, name: "Service User Experience", impact: "Extreme", description: "Totally unsatisfactory service user outcome resulting in long term effects, or extremely poor experience of care provision", value: 5},
  {id: 11, name: "Compliance with Standards (Statutory, Clinical, Professional & Management)", impact: "Negligible", description: "Minor non compliance with internal standards. Small number of minor issues requiring improvement ", value: 1},
  {id: 12, name: "Compliance with Standards (Statutory, Clinical, Professional & Management)", impact: "Minor", description: "Single failure to meet internal standards or follow protocol. Minor recommendations which can be easily addressed by local management", value: 2},
  {id: 13, name: "Compliance with Standards (Statutory, Clinical, Professional & Management)", impact: "Moderate", description: "Repeated failure to meet internal standards or follow protocols. Important recommendations that can be addressed with an appropriate management action plan. ", value: 3},
  {id: 14, name: "Compliance with Standards (Statutory, Clinical, Professional & Management)", impact: "Major", description: "Repeated failure to meet external standards. Failure to meet national norms and standards / Regulations (e.g. Mental Health, Child Care Act etc). Critical report or substantial number of significant findings and/or lack of adherence to regulations. ", value: 4},
  {id: 15, name: "Compliance with Standards (Statutory, Clinical, Professional & Management)", impact: "Extreme", description: "Gross failure to meet external standards Repeated failure to meet national norms and standards / regulations. Severely critical report with possible major reputational or financial implications. ", value: 5},
  {id: 16, name: "Objectives/Projects", impact: "Negligible", description: "Barely noticeable reduction in scope, quality or schedule.", value: 1},
  {id: 17, name: "Objectives/Projects", impact: "Minor", description: "Minor reduction in scope, quality or schedule.", value: 2},
  {id: 18, name: "Objectives/Projects", impact: "Moderate", description: "Reduction in scope or quality of project; project objectives or schedule.", value: 3},
  {id: 19, name: "Objectives/Projects", impact: "Major", description: "Significant project over – run.", value: 4},
  {id: 20, name: "Objectives/Projects", impact: "Extreme", description: "Inability to meet project objectives. Reputation of the organisation seriously damaged.", value: 5},
  {id: 21, name: "Business Continuity", impact: "Negligible", description: "Interruption in a service which does not impact on the delivery of service user care or the ability to continue to provide service.", value: 1},
  {id: 22, name: "Business Continuity", impact: "Minor", description: "Short term disruption to service with minor impact on service user care.", value: 2},
  {id: 23, name: "Business Continuity", impact: "Moderate", description: "Some disruption in service with unacceptable impact on service user care.       Temporary loss of ability to provide service", value: 3},
  {id: 24, name: "Business Continuity", impact: "Major", description: "Sustained loss of service which has serious impact on delivery of service user care or service resulting in major contingency plans being involved", value: 4},
  {id: 25, name: "Business Continuity", impact: "Extreme", description: "Permanent loss of core service or facility. Disruption to facility leading to significant ‘knock on’ effect ", value: 5},
  {id: 26, name: "Adverse publicity/ Reputation", impact: "Negligible", description: "Rumours, no media coverage. No public concerns voiced. Little effect on employees morale. No review/investigation necessary.", value: 1},
  {id: 27, name: "Adverse publicity/ Reputation", impact: "Minor", description: "Local media coverage – short term. Some public concern. Minor effect on employees morale / public attitudes. Internal review necessary.", value: 2},
  {id: 28, name: "Adverse publicity/ Reputation", impact: "Moderate", description: "Local media – adverse publicity. Significant effect on employees morale & public perception of the organisation. Public calls (at local level) for specific remedial actions. Comprehensive review/investigation necessary.", value: 3},
  {id: 29, name: "Adverse publicity/ Reputation", impact: "Major", description: "National media/ adverse publicity, less than 3 days. News stories & features in national papers. Local media – long term adverse publicity. Public confidence in the organisation undermined. HSE use of resources questioned. Minister may make comment. Possible questions in the Dáil. Public calls (at national level) for specific remedial actions to be taken possible HSE review/investigation", value: 4},
  {id: 30, name: "Adverse publicity/ Reputation", impact: "Extreme", description: "National/International media/ adverse publicity, > than 3 days. Editorial follows days of news stories & features in National papers. Public confidence in the organisation undermined. HSE use of resources questioned. CEO’s performance questioned. Calls for individual HSE officials to be sanctioned. Taoiseach/Minister forced to comment or intervene. Questions in the Dail. Public calls (at national level) for specific remedial actions to be taken. Court action. Public (independent) Inquiry. ", value: 5},
  {id: 31, name: "Financial Loss (per local Contact)", impact: "Negligible", description: "<€1k", value: 1},
  {id: 32, name: "Financial Loss (per local Contact)", impact: "Minor", description: "€1k – €10k", value: 2},
  {id: 33, name: "Financial Loss (per local Contact)", impact: "Moderate", description: "€10k – €100k", value: 3},
  {id: 34, name: "Financial Loss (per local Contact)", impact: "Major", description: "€100k – €1m", value: 4},
  {id: 35, name: "Financial Loss (per local Contact)", impact: "Extreme", description: ">€1m", value: 5},
  {id: 36, name: "Environment", impact: "Negligible", description: "Nuisance Release.", value: 1},
  {id: 37, name: "Environment", impact: "Minor", description: "On site release contained by organisation.", value: 2},
  {id: 38, name: "Environment", impact: "Moderate", description: "On site release contained by organisation.", value: 3},
  {id: 39, name: "Environment", impact: "Major", description: "Release affecting minimal off-site area requiring external assistance (fire brigade, radiation, protection service etc.)", value: 4},
  {id: 40, name: "Environment", impact: "Extreme", description: "Toxic release affecting off-site with detrimental effect requiring outside assistance.", value: 5},
  {id: 41, name: "", impact: "Negligible", description: "", value: 1},
  {id: 42, name: "", impact: "Minor", description: "", value: 2},
  {id: 43, name: "", impact: "Moderate", description: "", value: 3},
  {id: 44, name: "", impact: "Major", description: "", value: 4},
  {id: 45, name: "", impact: "Extreme", description: "", value: 5}])