source 'http://rubygems.org'

gem 'devise', '3.4.1'

gem 'rails4-autocomplete', '1.1.1'

gem 'commontator', '4.10.3'

gem 'jquery-ui-rails', '5.0.3'

# Document editor
gem 'tinymce-rails', '4.1.6'

# For file uploading
gem 'paperclip', '~> 4.2'

# Document version comparison
gem 'diffy', '~> 3.0.7'

# Unescape HTML in output of document version comparison
gem 'htmlentities', '~> 4.3.3'

gem 'faker'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks', '~> 2.5.3'
gem 'jquery-turbolinks', '~> 2.1.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'bootstrap_form'

gem 'nested_form'

gem 'bootstrap-will_paginate'

gem "mailboxer"

gem 'will_paginate'

gem 'dossier'

gem "chartkick"

gem 'jquery-tablesorter'

gem 'groupdate' #note, does not support SQLite

gem 'pdfjs_rails',:git => 'https://github.com/shyammohankanojia/pdfjs_rails.git'

# Upload PDFs and Images to AWS S3 
gem 'aws-sdk', '< 2.0'

#queuing system for rails 4.2+
gem 'delayed_job_active_record'

#enable client side validation
#gem 'html5_validators'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
#  gem 'spring'

  #solve db migrate problem
  gem 'tzinfo-data'

  #solving object type not support error
  gem 'coffee-script-source', '1.8.0'

  #gem for creating existing data to seed file
  gem 'seed_dump', :git => 'https://github.com/yuft/seed_dump.git'

  #gem for emailing
  gem 'actionmailer'

  gem "factory_girl"

  gem "rspec-rails"

  gem 'guard-rspec'

  gem 'spring-commands-rspec'

  gem 'vcr'

end

group :test do
  gem 'database_cleaner'
  gem 'capybara'
  gem 'shoulda-matchers', require: false
  gem 'webmock'
end

group :production do
  # gem 'pg', '0.12.2'
  gem 'pg'
  gem 'rails_12factor'
end
